#!/bin/bash
# Rename files that had the previous commit name to the new one

TESTS_DIR=lib_tests
read -r pre post
before=${pre:0:7}
after=${post:0:7}

[[ -e $TESTS_DIR/$before ]] || exit

echo "Renaming previous commit $before to $after"
mv $TESTS_DIR/"$before" $TESTS_DIR/"$after"
mv $TESTS_DIR/tracks-"$before" $TESTS_DIR/tracks-"$after"
mv $TESTS_DIR/album-"$before" $TESTS_DIR/album-"$after"
