#!/bin/sh

[ "$(git branch --show-current)" = dev ] || exit

commit=$(git rev-parse --short HEAD)
previous_commit=$(ls --sort time ./lib_tests -1 | grep '^[0-9a-z]{7}$' -E | head -1)

git diff --no-index lib_tests/"$previous_commit" lib_tests/dev && exit

cp -r lib_tests/dev lib_tests/"$commit"
sed -i 's/REFERENCE_DIR = .*/REFERENCE_DIR = "'"$commit"'"/' ./tests/test_lib.py
