#!/bin/bash
#
# url2json [-h] <bandcamp-url>
#
#       Parse given bandcamp url and print the resulting json.
#       By default, it outputs an indented/prettified json string
#       (which is used by the tests).
#       Use (human) flag -h to include colors and page it.
#       Ensure you have curl, and jq on your system.
#
# url2json https://hello.bandcamp.com/album/hi > ./tests/testcase.json
# url2json -h https://hello.bandcamp.com/album/hi
#
#       Note: Some lengthy fields are removed since they aren't currently parsed.
#             Feel free to adjust.
#

if [[ -z "$1" ]]; then
  sed -n '2,$s/^#/ /p' "$0"
else
  if [[ $1 == -h ]]; then
    help=1
    shift
  fi

  jqargs=(--sort-keys 'del(.comment, .sponsor, .albumRelease[0].offers)')
  curl -s "$1" | grep datePubl | {
    if (( help )); then
      jq -C "${jqargs[@]}" | less -R
    else
      jq "${jqargs[@]}"
    fi
  }
fi
